export const WORLD_CUP_NATIONS = [
  { flag: '🇺🇸', name: 'USA' },
  { flag: '🇨🇦', name: 'Canada' },
  { flag: '🇲🇽', name: 'Mexico' },
  { flag: '🇧🇷', name: 'Brazil' },
  { flag: '🇦🇷', name: 'Argentina' },
  { flag: '🇫🇷', name: 'France' },
  { flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: 'England' },
  { flag: '🇩🇪', name: 'Germany' },
  { flag: '🇪🇸', name: 'Spain' },
  { flag: '🇵🇹', name: 'Portugal' },
  { flag: '🇨🇴', name: 'Colombia' },
  { flag: '🇲🇦', name: 'Morocco' },
  { flag: '🇯🇵', name: 'Japan' },
  { flag: '🇳🇱', name: 'Netherlands' },
  { flag: '🇧🇪', name: 'Belgium' },
  { flag: '🇭🇷', name: 'Croatia' },
  { flag: '🇺🇾', name: 'Uruguay' },
  { flag: '🇷🇸', name: 'Serbia' },
  { flag: '🇨🇭', name: 'Switzerland' },
  { flag: '🇩🇰', name: 'Denmark' },
  { flag: '🇵🇱', name: 'Poland' },
  { flag: '🇸🇳', name: 'Senegal' },
  { flag: '🇦🇺', name: 'Australia' },
  { flag: '🇰🇷', name: 'South Korea' },
  { flag: '🇮🇷', name: 'Iran' },
  { flag: '🇸🇦', name: 'Saudi Arabia' },
  { flag: '🇪🇨', name: 'Ecuador' },
  { flag: '🇬🇭', name: 'Ghana' },
  { flag: '🇨🇲', name: 'Cameroon' },
  { flag: '🇹🇳', name: 'Tunisia' },
  { flag: '🇨🇷', name: 'Costa Rica' },
  { flag: '🇶🇦', name: 'Qatar' },
]
